server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bkdate?&serverTimezone=UTC
    username: usuario
    password: senha
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

